### ISSUE TITLE
Rebble Help Interactive Setup & Help

### ISSUE THREAD

**Issue by Willow-Systems** [pebble-dev/rebble-help#1]
- [x] Implement a single page application that:
    - [x] Works on desktop and phone browsers
    - [x] Includes a step-by-step follow-along guide for Rebble setup
    - [x] Can be extended by contributers (without writing more code) to provide support for more issues

**Comment by Willow-Systems** [comment]
@jwise @ishotjr Let me know what you think!

**Comment by jwise** [comment]
:tada: Grant accepted! The Rebble Alliance will grant $500 on completion of this work. :tada:

**Comment by Willow-Systems** [comment]
The now live help.rebble.io meets the criteria set out in this grant!

**We have OS-specific setup guides!** :tada: 
![image](https://user-images.githubusercontent.com/24474651/109683384-34144380-7b77-11eb-9c79-ef55b656ca0d.png)

**We have a mobile friendly UI:**
![image](https://user-images.githubusercontent.com/24474651/109683468-4b533100-7b77-11eb-9886-d826466d0a0f.png)

**It's Jekyll based, so contributing is as easy as writing markdown**
![image](https://user-images.githubusercontent.com/24474651/109683701-85243780-7b77-11eb-9736-6401aa775aac.png)

**There's even support for QR codes, only shown on desktop**
![image](https://user-images.githubusercontent.com/24474651/109683813-99683480-7b77-11eb-9ba6-a0b27c37d221.png)

**There's a search bar**
![image](https://user-images.githubusercontent.com/24474651/109684009-c3b9f200-7b77-11eb-8e57-90c2f6f91235.png)

**and a guide to contributing:**
https://help.rebble.io/contributing

**and it even works without Javascript, for that 0.0001% of users**
![image](https://user-images.githubusercontent.com/24474651/109684170-e9df9200-7b77-11eb-960f-c63cd73e72be.png)

**Comment by Willow-Systems** [comment]
Pinging @ishotjr and @jwise for review!

**Comment by ishotjr** [comment]
@Willow-Systems will do tonight - thank you! :sparkling_heart:

**Comment by ishotjr** [comment]
@Willow-Systems thank you! I'm getting caught up on Rebble stuff after a bit of a deluge, but have been prioritizing accounting/grants - this is very much on my list though, and I'm looking forward to it! :sparkling_heart:

**Comment by jwise** [comment]
🎉 I agree that this meets the criteria of the the submitted grant proposal!  And it's a great improvement, too.  We should link this from the HOWTO (or maybe replace the HOWTO entirely with it?).  And, of course, we should tweet about it!

cc: @ishotjr
